name: CI Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify your Python version

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # Run notebook tests with nbval
      - name: Run notebook tests
        run: |
          pip install nbval  # Ensure nbval is installed
          python -m pytest --nbval notebook.ipynb


  deploy:
    runs-on: ubuntu-latest
    needs: test  # Only run this job if the 'test' job succeeds

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for proper Git operations

      # Deploy to Hugging Face Space
      - name: Deploy to Hugging Face Space
        env:
          HF_TOKEN: ${{secrets.HF_TOKEN}}
        run: |
          git remote add space https://LostInHaze:$HF_TOKEN@huggingface.co/spaces/LostInHaze/demo
          git push --force space main
